_dim_ = 256
_ffn_dim_ = 512
_num_cams_ = 20
_num_levels_ = 4
_pos_dim_ = 128
anchor_z_ = 40
backend_args = None
cam_point_range = [
    -6.0,
    -6.0,
    -0.78,
    6.0,
    6.0,
    3.22,
]
class_names = (
    'ceiling',
    'floor',
    'wall',
    'window',
    'chair',
    'bed',
    'sofa',
    'table',
    'tv',
    'furniture',
    'objects',
)
custom_hooks = [
    dict(after_iter=True, type='EmptyCacheHook'),
]
data_root = '/data'
dataset_type = 'Scannetpp2xDataset'
default_hooks = dict(
    checkpoint=dict(interval=32, max_keep_ckpts=32, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'))
default_scope = 'embodiedscan'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
find_unused_parameters = True
launcher = 'none'
load_from = 'work_dirs/sliceocc/epoch_32.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
metainfo = dict(
    box_type_3d='euler-depth',
    classes=(
        'ceiling',
        'floor',
        'wall',
        'window',
        'chair',
        'bed',
        'sofa',
        'table',
        'tv',
        'furniture',
        'objects',
    ),
    occ_classes=(
        'ceiling',
        'floor',
        'wall',
        'window',
        'chair',
        'bed',
        'sofa',
        'table',
        'tv',
        'furniture',
        'objects',
    ))
model = dict(
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(checkpoint='torchvision://resnet50', type='Pretrained'),
        norm_cfg=dict(requires_grad=False, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='pytorch',
        type='mmdet.ResNet'),
    bbox_head=dict(
        in_channels=[
            128,
            128,
            128,
        ],
        num_classes=12,
        type='ImVoxelOccHead',
        up_ratio=4,
        use_semantic=True,
        volume_h=240,
        volume_w=240,
        volume_z=80),
    coord_type='DEPTH',
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='Det3DDataPreprocessor'),
    n_anchors=[
        60,
        60,
        40,
    ],
    n_voxels=[
        240,
        240,
        80,
    ],
    neck=dict(
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=4,
        out_channels=256,
        type='mmdet.FPN'),
    neck_3d=dict(
        in_channels=256,
        n_blocks=[
            1,
            1,
            1,
        ],
        out_channels=128,
        type='IndoorImVoxelNeck'),
    point_cloud_range=[
        -6.0,
        -6.0,
        -0.78,
        6.0,
        6.0,
        3.22,
    ],
    prior_generator=dict(
        ranges=[
            [
                -6.0,
                -6.0,
                -0.78,
                6.0,
                6.0,
                3.22,
            ],
        ],
        rotations=[
            0.0,
        ],
        type='AlignedAnchor3DRangeGenerator'),
    slicenet=dict(
        embed_dims=256,
        encoder=dict(
            num_layers=3,
            num_points_in_pillar=[
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
            ],
            pc_range=[
                -6.0,
                -6.0,
                -0.78,
                6.0,
                6.0,
                3.22,
            ],
            return_intermediate=False,
            slice_h=60,
            slice_num=[
                20,
                0,
                0,
            ],
            slice_w=60,
            slice_z=20,
            transformerlayers=dict(
                attn_cfgs=[
                    dict(
                        embed_dims=256,
                        num_levels=4,
                        num_slices=20,
                        tpv_h=60,
                        tpv_w=60,
                        tpv_z=20,
                        type='TPVCrossViewHybridAttention'),
                    dict(
                        deformable_attention=dict(
                            embed_dims=256,
                            floor_sampling_offset=False,
                            num_levels=4,
                            num_points=[
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                                8,
                            ],
                            num_slices=20,
                            num_z_anchors=[
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                                4,
                            ],
                            tpv_h=60,
                            tpv_w=60,
                            tpv_z=20,
                            type='TPVMSDeformableAttention3D'),
                        embed_dims=256,
                        num_cams=20,
                        num_slices=[
                            20,
                            0,
                            0,
                        ],
                        pc_range=[
                            -6.0,
                            -6.0,
                            -0.78,
                            6.0,
                            6.0,
                            3.22,
                        ],
                        tpv_h=60,
                        tpv_w=60,
                        tpv_z=20,
                        type='TPVImageCrossAttention'),
                ],
                feedforward_channels=512,
                ffn_dropout=0.1,
                operation_order=(
                    'self_attn',
                    'norm',
                    'cross_attn',
                    'norm',
                    'ffn',
                    'norm',
                ),
                type='TPVFormerLayer'),
            type='SliceOccEncoder'),
        num_cams=20,
        num_feature_levels=4,
        pc_range=[
            -6.0,
            -6.0,
            -0.78,
            6.0,
            6.0,
            3.22,
        ],
        positional_encoding=dict(
            col_num_embed=60,
            num_feats=128,
            row_num_embed=60,
            type='LearnedPositionalEncoding'),
        slice_h=60,
        slice_num=[
            20,
            0,
            0,
        ],
        slice_w=60,
        slice_z=40,
        type='SliceOccHead',
        use_semantic=True),
    type='DenseSliceOccPredictor',
    use_valid_mask=False,
    use_xyz_feat=True)
n_points = 100000
nbr_class = 12
num_points = [
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
]
num_points_h = []
num_points_in_pillar = [
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
]
num_points_in_pillar_h = []
num_points_in_pillar_w = []
num_points_in_pillar_z = [
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
]
num_points_w = []
num_points_z = [
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
]
num_slices_ = [
    20,
    0,
    0,
]
num_slices_h = 0
num_slices_w = 0
num_slices_z = 20
optim_wrapper = dict(
    clip_grad=dict(max_norm=35.0, norm_type=2),
    optimizer=dict(lr=0.0001, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
out_h = 240
out_w = 240
out_z = 80
param_scheduler = dict(
    begin=0,
    by_epoch=True,
    end=32,
    gamma=0.1,
    milestones=[
        22,
        26,
    ],
    type='MultiStepLR')
point_cloud_range = [
    -6.0,
    -6.0,
    -0.78,
    6.0,
    6.0,
    3.22,
]
prior_generator = dict(
    ranges=[
        [
            -6.0,
            -6.0,
            -0.78,
            6.0,
            6.0,
            3.22,
        ],
    ],
    rotations=[
        0.0,
    ],
    type='AlignedAnchor3DRangeGenerator')
resume = False
scale_h = 1
scale_w = 1
scale_z = 1
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='scannetpp_infos_2x_val.pkl',
        box_type_3d='Euler-Depth',
        data_root='/data',
        filter_empty_gt=True,
        metainfo=dict(
            box_type_3d='euler-depth',
            classes=(
                'ceiling',
                'floor',
                'wall',
                'window',
                'chair',
                'bed',
                'sofa',
                'table',
                'tv',
                'furniture',
                'objects',
            ),
            occ_classes=(
                'ceiling',
                'floor',
                'wall',
                'window',
                'chair',
                'bed',
                'sofa',
                'table',
                'tv',
                'furniture',
                'objects',
            )),
        pipeline=[
            dict(
                type='LoadAnnotations3D',
                with_occupancy=True,
                with_visible_occupancy_masks=False),
            dict(
                n_images=20,
                transforms=[
                    dict(backend_args=None, type='LoadImageFromFile'),
                    dict(keep_ratio=False, scale=(
                        480,
                        480,
                    ), type='Resize'),
                ],
                type='MultiViewPipeline'),
            dict(
                keys=[
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_occupancy',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='Scannetpp2xDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(type='OccupancyMetric')
test_pipeline = [
    dict(
        type='LoadAnnotations3D',
        with_occupancy=True,
        with_visible_occupancy_masks=False),
    dict(
        n_images=20,
        transforms=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=False, scale=(
                480,
                480,
            ), type='Resize'),
        ],
        type='MultiViewPipeline'),
    dict(
        keys=[
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_occupancy',
        ],
        type='Pack3DDetInputs'),
]
tpv_h_ = 60
tpv_w_ = 60
tpv_z_ = 20
train_cfg = dict(max_epochs=32, type='EpochBasedTrainLoop', val_interval=8)
train_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='scannetpp_infos_2x_train.pkl',
        box_type_3d='Euler-Depth',
        data_root='/data',
        filter_empty_gt=True,
        metainfo=dict(
            box_type_3d='euler-depth',
            classes=(
                'ceiling',
                'floor',
                'wall',
                'window',
                'chair',
                'bed',
                'sofa',
                'table',
                'tv',
                'furniture',
                'objects',
            ),
            occ_classes=(
                'ceiling',
                'floor',
                'wall',
                'window',
                'chair',
                'bed',
                'sofa',
                'table',
                'tv',
                'furniture',
                'objects',
            )),
        pipeline=[
            dict(
                type='LoadAnnotations3D',
                with_occupancy=True,
                with_visible_occupancy_masks=False),
            dict(
                n_images=20,
                transforms=[
                    dict(backend_args=None, type='LoadImageFromFile'),
                    dict(keep_ratio=False, scale=(
                        480,
                        480,
                    ), type='Resize'),
                ],
                type='MultiViewPipeline'),
            dict(
                keys=[
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_occupancy',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=False,
        type='Scannetpp2xDataset'),
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        type='LoadAnnotations3D',
        with_occupancy=True,
        with_visible_occupancy_masks=False),
    dict(
        n_images=20,
        transforms=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=False, scale=(
                480,
                480,
            ), type='Resize'),
        ],
        type='MultiViewPipeline'),
    dict(
        keys=[
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_occupancy',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='scannetpp_infos_2x_val.pkl',
        box_type_3d='Euler-Depth',
        data_root='/data',
        filter_empty_gt=True,
        metainfo=dict(
            box_type_3d='euler-depth',
            classes=(
                'ceiling',
                'floor',
                'wall',
                'window',
                'chair',
                'bed',
                'sofa',
                'table',
                'tv',
                'furniture',
                'objects',
            ),
            occ_classes=(
                'ceiling',
                'floor',
                'wall',
                'window',
                'chair',
                'bed',
                'sofa',
                'table',
                'tv',
                'furniture',
                'objects',
            )),
        pipeline=[
            dict(
                type='LoadAnnotations3D',
                with_occupancy=True,
                with_visible_occupancy_masks=False),
            dict(
                n_images=20,
                transforms=[
                    dict(backend_args=None, type='LoadImageFromFile'),
                    dict(keep_ratio=False, scale=(
                        480,
                        480,
                    ), type='Resize'),
                ],
                type='MultiViewPipeline'),
            dict(
                keys=[
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_occupancy',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='Scannetpp2xDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(type='OccupancyMetric')
visualizer = dict(
    save_dir='temp_dir',
    type='EmbodiedScanBaseVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = './work_dirs/mv-occ_8xb1_sliceformer-occ2x-11class'
